export default [
  // POI - polygon start
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'skyblue',
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['arts_centre', 'fountain', 'gate', 'palace', 'chungmoo art hall'],
      true,
      false,
    ],
    id: 'poi-attraction-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'skyblue',
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      [
        'restaurant',
        'cafe',
        'marketplace',
        'fast_food',
        'bar',
        'pub',
        'casino',
        'cinema',
        '',
      ],
      true,
      false,
    ],
    id: 'poi-business-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'skyblue',
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      [
        'fire_station',
        'post_office',
        'police',
        'townhall',
        'public',
        'ranger_station',
        'government',
        'bunker',
      ],
      true,
      false,
    ],
    id: 'poi-government-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'lightgrey',
      'fill-opacity': 0.5,
    },
    filter: ['match', ['get', 'type'], ['hospital', 'pharmacy'], true, false],
    id: 'poi-medical-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'red',
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['place_of_worship', 'cathedral', 'chapel', 'church'],
      true,
      false,
    ],
    id: 'poi-worship-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'brown',
      'fill-opacity': 0.5,
    },
    filter: [
      'in',
      'type',
      'college',
      'university',
      'language_school',
      'school',
      'kindergarten',
    ],
    id: 'poi-school-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'lightgrey',
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['toilets', 'social_facility', 'conference_centre'],
      true,
      false,
    ],
    id: 'poi-etc-polygon',
  },
  {
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': 'skyblue',
      'fill-opacity': 0.5,
    },
    filter: ['match', ['get', 'type'], 'swimming_pool', true, false],
    id: 'poi-sports-polygon',
  },
  // POI - polygon end
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'brown',
    },
    filter: [
      'match',
      ['get', 'type'],
      ['milestone', 'arts_centre', 'fountain'],
      true,
      false,
    ],
    id: 'poi-attraction',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'blue',
    },
    filter: [
      'match',
      ['get', 'type'],
      [
        'cinema',
        'bar',
        'post_box',
        'restaurant',
        'theatre',
        'studio',
        'bureau_de_change',
        'marketplace',
        'fast_food',
        'toll_booth',
        'charging_station',
        'social_facility',
        'nightclub',
        'food_court',
        'car_rental',
        'bicycle_rental',
        'pub',
        'bank',
        'ice_cream',
        'fuel',
      ],
      true,
      false,
    ],
    id: 'poi-business',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: [
      'match',
      ['get', 'type'],
      [
        'townhall',
        'social_centre',
        'post_office',
        'shelter',
        'embassy',
        'police',
      ],
      true,
      false,
    ],
    id: 'poi-government',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: [
      'match',
      ['get', 'type'],
      ['hospital', 'doctors', 'clinic', 'dentist', 'pharmacy'],
      true,
      false,
    ],
    id: 'poi-medical',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: [
      'match',
      ['get', 'type'],
      ['waste_basket', 'tree', 'rest_area'],
      true,
      false,
    ],
    id: 'poi-park',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: ['match', ['get', 'type'], 'place_of_worship'],
    id: 'poi-worship',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: [
      'match',
      ['get', 'type'],
      ['school', 'kindergarten', 'college'],
      true,
      false,
    ],
    id: 'poi-school',
  },
  {
    type: 'symbol',
    source: 'poi_source',
    'source-layer': 'poi',
    layout: {
      'text-field': ['get', 'name'],
      visibility: 'visible',
    },
    paint: {
      'text-color': 'green',
    },
    filter: [
      'in',
      'type',
      'parking',
      'crossing',
      'traffic_signal',
      'mini_roundabout',
      'bench',
      'sally port',
      'block',
      'street_lamp',
      'bollard',
      'lift_gate',
      'gate',
      'elevator',
      'toilets',
      'water_point',
      'spring',
      'atm',
    ],
    id: 'poi-etc',
  },
];
