export default [
  {
    type: 'line',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': 'brown',
      'line-width': 4,
    },
    filter: ['match', ['get', 'type'], 'city_wall', true, false],
    id: 'city-wall',
  },
  {
    type: 'line',
    source: 'line_source',
    'source-layer': 'line',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': '#ff00ff',
      'line-width': 1,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['road', 'primary', 'secondary', 'teritiary'],
      true,
      false,
    ],
    id: 'road-arterial',
  },
  {
    type: 'line',
    source: 'line_source',
    'source-layer': 'line',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': 'blue',
    },
    filter: [
      'match',
      ['get', 'type'],
      ['cycleway', 'path', 'living_street', 'service'],
      true,
      false,
    ],
    id: 'road-local',
  },
  {
    type: 'line',
    source: 'line_source',
    'source-layer': 'line',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'line-color': 'red',
      'line-width': 1,
    },
    filter: ['match', ['get', 'type'], ['pedestrian', 'footway'], true, false],
    id: 'road-footway',
  },
  {
    id: 'road-arterial-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'road',
    metadata: {},
    minzoom: 10,
    filter: [
      'step',
      ['zoom'],
      [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk', 'primary', 'secondary'],
        true,
        false,
      ],
      12,
      [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk', 'primary', 'secondary'],
        true,
        false,
      ],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        10,
        [
          'match',
          ['get', 'class'],
          ['motorway', 'trunk', 'primary', 'secondary'],
          10,
          ['motorway_link', 'trunk_link', 'primary_link', 'secondary_link'],
          9,
          6.5,
        ],
        18,
        [
          'match',
          ['get', 'class'],
          ['motorway', 'trunk', 'primary', 'secondary'],
          16,
          ['motorway_link', 'trunk_link', 'primary_link', 'secondary_link'],
          14,
          13,
        ],
      ],
      'text-max-angle': 30,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'symbol-placement': 'line',
      'text-padding': 1,
      'text-rotation-alignment': 'map',
      'text-pitch-alignment': 'viewport',
      'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      'text-letter-spacing': 0.01,
    },
    paint: {
      'text-color': [
        'match',
        ['get', 'class'],
        'ferry',
        'hsl(230, 48%, 44%)',
        'hsl(0, 0%, 0%)',
      ],
      'text-halo-color': [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk'],
        'hsla(0, 0%, 100%, 0.75)',
        'hsl(0, 0%, 100%)',
      ],
      'text-halo-width': 1,
      'text-halo-blur': 1,
    },
  },
  {
    id: 'road-local-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'road',
    metadata: {},
    minzoom: 10,
    filter: [
      'step',
      ['zoom'],
      ['match', ['get', 'class'], ['tertiary'], true, false],
      12,
      ['match', ['get', 'class'], ['tertiary', 'street'], true, false],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        10,
        [
          'match',
          ['get', 'class'],
          ['tertiary'],
          10,
          ['tertiary_link', 'street'],
          9,
          6.5,
        ],
        18,
        [
          'match',
          ['get', 'class'],
          ['tertiary'],
          16,
          ['tertiary_link', 'street'],
          14,
          13,
        ],
      ],
      'text-max-angle': 30,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'symbol-placement': 'line',
      'text-padding': 1,
      'text-rotation-alignment': 'map',
      'text-pitch-alignment': 'viewport',
      'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      'text-letter-spacing': 0.01,
    },
    paint: {
      'text-color': [
        'match',
        ['get', 'class'],
        'ferry',
        'hsl(230, 48%, 44%)',
        'hsl(0, 0%, 0%)',
      ],
      'text-halo-color': [
        'match',
        ['get', 'class'],
        ['ferry'],
        'hsla(0, 0%, 100%, 0.75)',
        'hsl(0, 0%, 100%)',
      ],
      'text-halo-width': 1,
      'text-halo-blur': 1,
    },
  },
  {
    id: 'road-sidewalk-label',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'road',
    metadata: {},
    minzoom: 10,
    filter: [
      'match',
      ['get', 'class'],
      ['pedestrian', 'street_limited'],
      true,
      false,
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['linear'],
        ['zoom'],
        10,
        ['match', ['get', 'class'], ['pedestrian', 'street_limited'], 9, 6.5],
        18,
        ['match', ['get', 'class'], ['pedestrian', 'street_limited'], 14, 13],
      ],
      'text-max-angle': 30,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'symbol-placement': 'line',
      'text-padding': 1,
      'text-rotation-alignment': 'map',
      'text-pitch-alignment': 'viewport',
      'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      'text-letter-spacing': 0.01,
    },
    paint: {
      'text-color': [
        'match',
        ['get', 'class'],
        'ferry',
        'hsl(230, 48%, 44%)',
        'hsl(0, 0%, 0%)',
      ],
      'text-halo-color': [
        'match',
        ['get', 'class'],
        ['motorway', 'trunk'],
        'hsla(0, 0%, 100%, 0.75)',
        'ferry',
        'hsl(196, 80%, 70%)',
        'hsl(0, 0%, 100%)',
      ],
      'text-halo-width': 1,
      'text-halo-blur': 1,
    },
  },
];
