interface LayersColorType {
  [name: string]: string;
}

const layersColor: LayersColorType = {
  'poi-all-labelText-fill': 'transparent',
  'poi-all-labelText-stroke': 'transparent',
  'poi-all-labelIcon': 'transparent',
  'poi-landmark-labelText-fill': 'hsl(26, 25%, 32%)',
  'poi-landmark-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-landmark-labelIcon': 'transparent',
  'poi-business-labelText-fill': 'hsl(22, 55%, 55%)',
  'poi-business-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-business-labelIcon': 'transparent',
  'poi-government-labelText-fill': 'hsl(26, 25%, 32%)',
  'poi-government-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-government-labelIcon': 'transparent',
  'poi-medical-labelText-fill': 'hsl(340, 39%, 42%)',
  'poi-medical-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-medical-labelIcon': 'transparent',
  'poi-park-labelText-fill': 'hsl(100, 45%, 37%)',
  'poi-park-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-park-labelIcon': 'transparent',
  'poi-worship-labelText-fill': 'hsl(26, 25%, 32%)',
  'poi-worship-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-worship-labelIcon': 'transparent',
  'poi-school-labelText-fill': 'hsl(51, 40%, 40%)',
  'poi-school-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-school-labelIcon': 'transparent',
  'poi-sports-labelText-fill': 'hsl(26, 25%, 32%)',
  'poi-sports-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-sports-labelIcon': 'transparent',
  'poi-etc-labelText-fill': 'hsl(26, 25%, 32%)',
  'poi-etc-labelText-stroke': 'hsl(0, 0%, 100%)',
  'poi-etc-labelIcon': 'transparent',
  'administrative-all-section-fill': 'transparent',
  'administrative-all-section-stroke': 'transparent',
  'administrative-all-labelText-fill': 'transparent',
  'administrative-all-labelText-stroke': 'transparent',
  'administrative-country-section-fill': 'transparent',
  'administrative-country-section-stroke': 'hsl(230, 8%, 51%)',
  'administrative-country-labelText-fill': 'hsl(0, 0%, 0%)',
  'administrative-country-labelText-stroke': 'hsl(0, 0%, 100%)',
  'administrative-state-section-fill': 'transparent',
  'administrative-state-section-stroke': 'hsl(230, 14%, 77%)',
  'administrative-state-labelText-fill': 'hsl(0, 0%, 0%)',
  'administrative-state-labelText-stroke': 'hsl(0, 0%, 100%)',
  'administrative-locality-section-fill': 'transparent',
  'administrative-locality-section-stroke': 'transparent',
  'administrative-locality-labelText-fill': 'hsl(0, 0%, 0%)',
  'administrative-locality-labelText-stroke': 'hsl(0, 0%, 100%)',
  'transit-all-section-fill': 'transparent',
  'transit-all-section-stroke': 'transparent',
  'transit-all-labelText-fill': 'transparent',
  'transit-all-labelText-stroke': 'transparent',
  'transit-airport-section-fill': 'hsl(40, 97%, 64%)',
  'transit-airport-section-stroke': 'hsl(230, 23%, 82%)',
  'transit-airport-labelText-fill': 'hsl(0, 69%, 50%)',
  'transit-airport-labelText-stroke': 'hsl(0, 0%, 100%)',
  'transit-bus-section-fill': 'transparent',
  'transit-bus-section-stroke': 'transparent',
  'transit-bus-labelText-fill': 'hsl(13, 68%, 63%)',
  'transit-bus-labelText-stroke': 'hsl(0, 0%, 100%)',
  'transit-rail-section-fill': 'hsl(234, 20%, 30%)',
  'transit-rail-section-stroke': 'transparent',
  'transit-rail-labelText-fill': 'transparent',
  'transit-rail-labelText-stroke': 'transparent',
  'transit-subway-section-fill': 'hsl(192, 70%, 43%)',
  'transit-subway-section-stroke': 'transparent',
  'transit-subway-labelText-fill': 'transparent',
  'transit-subway-labelText-stroke': 'transparent',
  'water-all-section-fill': 'hsl(205, 87%, 76%)',
  'water-all-section-stroke': 'transparent',
  'water-all-labelText-fill': 'hsl(230, 48%, 44%)',
  'water-all-labelText-stroke': 'transparent',
};

export default layersColor;
