import defaultStyle from '../defaultStyle';

const initLayers = {
  version: 8,
  name: 'Mapbox Streets',
  metadata: {
    'mapbox:type': 'default',
    'mapbox:origin': 'streets-v11',
    'mapbox:autocomposite': true,
    'mapbox:groups': {
      '1444855786460.0557': { name: 'Roads', collapsed: true },
      '1444934295202.7542': { name: 'Admin boundaries', collapsed: true },
      '1444855799204.86': { name: 'Bridges', collapsed: true },
      '1444855769305.6016': { name: 'Tunnels', collapsed: true },
    },
  },
  sources: {
    composite: {
      url: 'mapbox://mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2',
      type: 'vector',
    },
    polygon_source: {
      tiles: ['http://110.93.147.18:8080/boostcamp/polygon/{x}/{y}/{z}'],
      type: 'vector',
    },
    line_source: {
      tiles: ['http://110.93.147.18:8080/boostcamp/line/{x}/{y}/{z}'],
      type: 'vector',
    },
    poi_source: {
      tiles: ['http://110.93.147.18:8080/boostcamp/poi/{x}/{y}/{z}'],
      type: 'vector',
    },
  },
  center: [0, 0],
  zoom: 3,
  sprite: 'mapbox://sprites/mapbox/streets-v11',
  glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'landscape-landcover-section-fill',
      type: 'background',
      metadata: {},
      layout: {},
      paint: {
        'background-color':
          defaultStyle.landscape.landcover.section?.fill.color,
      },
    },
    {
      id: 'landscape-landcover-section-fill-2',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'landcover',
      maxzoom: 7,
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
        'fill-opacity': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          2,
          0.3,
          7,
          0,
        ],
        'fill-antialias': false,
      },
    },
    {
      id: 'landscape-landcover-section-fill-4',
      type: 'fill',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
        'fill-opacity': 0.5,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['sand', 'heath', 'grassland'],
        true,
        false,
      ],
    },
    {
      id: 'landscape-landcover-section-fill-5',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'structure',
      minzoom: 13,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['==', ['get', 'class'], 'land'],
      ],
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
      },
    },
    {
      id: 'landscape-landcover-section-stroke',
      type: 'line',
      metadata: {},
      source: 'composite',
      'source-layer': 'structure',
      minzoom: 13,
      filter: [
        'all',
        ['==', ['geometry-type'], 'LineString'],
        ['==', ['get', 'class'], 'land'],
      ],
      layout: { 'line-cap': 'round' },
      paint: {
        'line-width': defaultStyle.landscape.landcover.section?.stroke.weight,
        'line-color': defaultStyle.landscape.landcover.section?.stroke.color,
      },
    },
    {
      id: 'landscape-mountain-section-fill',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'hillshade',
      maxzoom: 16,
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.mountain.section?.fill.color,
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          ['match', ['get', 'level'], [67, 56], 0.06, [89, 78], 0.05, 0.12],
          16,
          0,
        ],
        'fill-antialias': false,
      },
    },
    {
      id: 'landscape-natural-section-fill',
      type: 'fill',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.landscape.natural.section?.fill.color,
        'fill-opacity': 0.5,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['wood', 'scrub', 'bare_rock'],
        true,
        false,
      ],
    },
    {
      id: 'landscape-natural-section-fill-2',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'landuse_overlay',
      minzoom: 5,
      filter: ['==', ['get', 'class'], 'national_park'],
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.natural.section?.fill.color,
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0,
          6,
          0.5,
          10,
          0.5,
        ],
      },
    },
    {
      id: 'landscape-humanmade-section-fill',
      type: 'fill',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.landscape.humanmade.section?.fill.color,
        'fill-opacity': 0.7,
      },
      filter: [
        'in',
        'type',
        'civic',
        'construction',
        'gate',
        'palace',
        'parking',
        'riverbank',
        'station',
        'steps',
        'train_station',
        'shrine',
        'retaining_wall',
        'smoking_area',
        'city_gate',
        'terrace',
        'shelter',
        'wall',
        'fence',
        'toll_booth',
        'kerb',
        'bench',
        'footway',
        'pedestrian',
        'parking',
        'fountain',
        'gate',
        '',
      ],
    },
    {
      id: 'landscape-humanmade-section-stroke',
      type: 'line',
      metadata: {},
      source: 'composite',
      'source-layer': 'landuse',
      minzoom: 15,
      filter: ['==', ['get', 'class'], 'pitch'],
      layout: {},
      paint: {
        'line-color': defaultStyle.landscape.humanmade.section?.stroke.color,
      },
    },
    {
      id: 'landscape-building-section-stroke',
      type: 'line',
      metadata: {},
      source: 'composite',
      'source-layer': 'building',
      minzoom: 15,
      filter: [
        'all',
        ['!=', ['get', 'type'], 'building:part'],
        ['==', ['get', 'underground'], 'false'],
      ],
      layout: {},
      paint: {
        'line-color': defaultStyle.landscape.building.section?.stroke.color,
        'line-width': defaultStyle.landscape.building.section?.stroke.weight,
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
      },
    },
    {
      id: 'landscape-building-section-fill',
      type: 'fill',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.landscape.building.section?.fill.color,
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
        'fill-outline-color': 'hsl(35, 8%, 80%)',
      },
      filter: [
        'in',
        'type',
        'apartments',
        'bunker',
        'cathedral',
        'chapel',
        'childcare',
        'chungmoo art hall',
        'church',
        'courthouse',
        'government',
        'hospital',
        'hotel',
        'house',
        'kindergarten',
        'public',
        'ranger_station',
        'residential',
        'roof',
        'school',
        'shed',
        'shelter',
        'university',
        'warehouse',
        'company',
        'conference_centre',
        'pavilion',
        'swimming_pool',
        'office',
        'dormitory',
        'public_bath',
        'community_centre',
        'theatre',
        'fire_station',
        'post_office',
        'police',
        'townhall',
        'public',
        'college',
        'language_school',
        'arts_centre',
        'palace',
        'toilets',
        'social_facility',
        'restaurant',
        'cafe',
        'marketplace',
        'fast_food',
        'bar',
        'pub',
        'casino',
        'cinema',
        '',
      ],
    },
    {
      id: 'landscape-building-section-fill-2',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'building',
      minzoom: 15,
      filter: [
        'all',
        ['!=', ['get', 'type'], 'building:part'],
        ['==', ['get', 'underground'], 'false'],
      ],
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.building.section?.fill.color,
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
        'fill-outline-color': 'hsl(35, 6%, 79%)',
      },
    },
    {
      id: 'landscape-natural-section-fill-3',
      type: 'fill',
      metadata: {},
      source: 'composite',
      'source-layer': 'landuse',
      minzoom: 5,
      filter: [
        'match',
        ['get', 'class'],
        [
          'park',
          'airport',
          'cemetery',
          'glacier',
          'hospital',
          'pitch',
          'sand',
          'school',
        ],
        true,
        false,
      ],
      layout: {},
      paint: {
        'fill-color': defaultStyle.landscape.natural.section?.fill.color,
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0,
          6,
          ['match', ['get', 'class'], 'glacier', 0.5, 1],
        ],
      },
    },
    {
      id: 'water-all-section-fill-1',
      type: 'fill',
      source: 'composite',
      'source-layer': 'water',
      layout: {},
      paint: {
        'fill-color': defaultStyle.water.all.section?.fill.color,
        'fill-translate': [
          'interpolate',
          ['exponential', 1.2],
          ['zoom'],
          7,
          ['literal', [0, 0]],
          16,
          ['literal', [-1, -1]],
        ],
        'fill-translate-anchor': 'viewport',
      },
    },
    {
      id: 'water-all-section-fill-3',
      type: 'fill',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.water.all.section?.fill.color,
        'fill-opacity': 1,
        'fill-translate': [
          'interpolate',
          ['linear', 1],
          ['zoom'],
          7,
          ['literal', [0, 0]],
          16,
          ['literal', [-1, -1]],
        ],
      },
      filter: ['==', ['get', 'type'], 'water'],
    },
    {
      id: 'water-all-section-fill-2',
      type: 'fill',
      source: 'composite',
      'source-layer': 'water',
      layout: {},
      paint: { 'fill-color': defaultStyle.water.all.section?.fill.color },
    },
    {
      id: 'road-arterial-section-stroke-1',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['==', ['get', 'class'], 'primary'],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          10,
          1,
          18,
          2,
        ],
        'line-color': defaultStyle.road.arterial.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
        'line-opacity': ['step', ['zoom'], 0, 10, 1],
      },
    },
    {
      id: 'road-arterial-section-stroke-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          10,
          1,
          18,
          2,
        ],
        'line-color': defaultStyle.road.arterial.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
        'line-opacity': ['step', ['zoom'], 0, 10, 1],
      },
    },
    {
      id: 'road-highway-section-stroke-1',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['match', ['get', 'class'], ['motorway', 'trunk'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-color': defaultStyle.road.highway.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
        'line-opacity': [
          'step',
          ['zoom'],
          ['match', ['get', 'class'], 'motorway', 1, 0],
          6,
          1,
        ],
      },
    },
    {
      id: 'road-local-section-stroke-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 13,
      filter: [
        'all',
        [
          'step',
          ['zoom'],
          ['==', ['get', 'class'], 'track'],
          14,
          [
            'match',
            ['get', 'class'],
            ['track', 'secondary_link', 'tertiary_link', 'service'],
            true,
            false,
          ],
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.75,
          20,
          2,
        ],
        'line-color': defaultStyle.road.local.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-highway-section-stroke-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        [
          'match',
          ['get', 'class'],
          ['motorway_link', 'trunk_link'],
          true,
          false,
        ],
        ['<=', ['get', 'layer'], 1],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          10,
          1,
          18,
          2,
        ],
        'line-color': defaultStyle.road.highway.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
      },
    },
    {
      id: 'road-arterial-section-stroke-6',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        [
          'match',
          ['get', 'class'],
          ['primary', 'secondary', 'tertiary'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          10,
          1,
          18,
          2,
        ],
        'line-color': defaultStyle.road.arterial.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
        'line-opacity': ['step', ['zoom'], 0, 10, 1],
      },
    },
    {
      id: 'road-local-section-stroke-1',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 11,
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['street', 'street_limited', 'primary_link'],
          true,
          false,
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.75,
          20,
          2,
        ],
        'line-color': defaultStyle.road.local.section?.stroke.color,
        'line-gap-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-sidewalk-section-stroke-1',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['get', 'class'], 'pedestrian'],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          2,
          18,
          14.5,
        ],
        'line-color': defaultStyle.road.sidewalk.section?.stroke.color,
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-arterial-section-fill-1',
      type: 'fill',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        [
          'match',
          ['get', 'class'],
          [
            'primary',
            'secondary',
            'tertiary',
            'primary_link',
            'secondary_link',
            'tertiary_link',
          ],
          true,
          false,
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
      ],
      paint: {
        'fill-color': defaultStyle.road.arterial.section?.fill.color,
        'fill-outline-color': '#d6d9e6',
      },
    },
    {
      id: 'road-arterial-section-fill-2',
      type: 'line',
      source: 'line_source',
      'source-layer': 'line',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': defaultStyle.road.arterial.section?.fill.color,
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
      },
      filter: [
        'match',
        ['get', 'type'],
        ['road', 'primary', 'secondary', 'teritiary'],
        true,
        false,
      ],
    },
    {
      id: 'road-arterial-section-fill-3',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['==', ['get', 'class'], 'primary'],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
      },
    },
    {
      id: 'road-arterial-section-fill-4',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['match', ['get', 'class'], ['secondary', 'tertiary'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
      },
    },
    {
      id: 'road-highway-section-fill-1',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      filter: [
        'all',
        ['match', ['get', 'class'], ['motorway', 'trunk'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-arterial-section-fill-7',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 13,
      filter: [
        'all',
        [
          'step',
          ['zoom'],
          ['==', ['get', 'class'], 'track'],
          14,
          [
            'match',
            ['get', 'class'],
            ['track', 'secondary_link', 'tertiary_link', 'service'],
            true,
            false,
          ],
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
        'line-opacity': ['step', ['zoom'], 1, 14, 0],
      },
    },
    {
      id: 'road-highway-section-fill-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 10,
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['motorway_link', 'trunk_link'],
          true,
          false,
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-highway-section-fill-4',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        ['match', ['get', 'class'], ['motorway', 'trunk'], true, false],
        ['<=', ['get', 'layer'], 1],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-highway-section-fill-5',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        ['>=', ['get', 'layer'], 2],
        ['match', ['get', 'class'], ['motorway', 'trunk'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-highway-section-fill-6',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        [
          'match',
          ['get', 'class'],
          ['motorway_link', 'trunk_link'],
          true,
          false,
        ],
        ['<=', ['get', 'layer'], 1],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          0.75,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-highway-section-fill-7',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        ['>=', ['get', 'layer'], 2],
        [
          'match',
          ['get', 'class'],
          ['motorway_link', 'trunk_link'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.highway.section?.fill.color,
      },
    },
    {
      id: 'road-arterial-section-fill-13',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        ['==', ['get', 'class'], 'path'],
        ['!=', ['get', 'type'], 'steps'],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [1, 0]],
          15,
          ['literal', [1.75, 1]],
          16,
          ['literal', [1, 0.75]],
          17,
          ['literal', [1, 0.5]],
        ],
      },
    },
    {
      id: 'road-arterial-section-fill-14',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        ['==', ['get', 'class'], 'path'],
        ['!=', ['get', 'type'], 'steps'],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-arterial-section-fill-15',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855799204.86' },
      minzoom: 13,
      filter: [
        'all',
        ['==', ['get', 'structure'], 'bridge'],
        [
          'match',
          ['get', 'class'],
          ['primary', 'secondary', 'tertiary'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          5,
          1,
          18,
          32,
        ],
        'line-color': defaultStyle.road.arterial.section?.fill.color,
      },
    },
    {
      id: 'road-local-section-fill-1',
      type: 'fill',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['match', ['get', 'class'], ['street'], true, false],
      ],
      paint: {
        'fill-color': defaultStyle.road.local.section?.fill.color,
        'fill-outline-color': '#d6d9e6',
      },
    },
    {
      id: 'road-local-section-fill-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      minzoom: 8,
      filter: ['==', ['get', 'type'], 'ferry'],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-color': defaultStyle.road.local.section?.fill.color,
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [1, 0]],
          13,
          ['literal', [12, 4]],
        ],
      },
    },
    {
      id: 'road-local-section-fill-3',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      filter: ['==', ['get', 'type'], 'ferry_auto'],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': defaultStyle.road.local.section?.fill.color,
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
      },
    },
    {
      id: 'road-local-section-fill-4',
      type: 'line',
      source: 'line_source',
      'source-layer': 'line',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-color': defaultStyle.road.local.section?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['cycleway', 'path', 'living_street', 'service'],
        true,
        false,
      ],
    },
    {
      id: 'road-local-section-fill-5',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 11,
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['street', 'street_limited', 'primary_link'],
          true,
          false,
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-color': defaultStyle.road.local.section?.fill.color,
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-local-section-fill-6',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 13,
      filter: [
        'all',
        [
          'step',
          ['zoom'],
          ['==', ['get', 'class'], 'track'],
          14,
          [
            'match',
            ['get', 'class'],
            ['track', 'secondary_link', 'tertiary_link', 'service'],
            true,
            false,
          ],
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          12,
          0.5,
          14,
          2,
          18,
          18,
        ],
        'line-color': defaultStyle.road.local.section?.fill.color,
        'line-opacity': ['step', ['zoom'], 0, 14, 1],
      },
    },
    {
      id: 'road-sidewalk-section-fill-1',
      type: 'fill',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
      ],
      paint: {
        'fill-color': defaultStyle.road.sidewalk.section?.fill.color,
        'fill-outline-color': 'hsl(230, 26%, 88%)',
      },
    },
    {
      id: 'road-sidewalk-section-fill-2',
      type: 'fill',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
      ],
      paint: {
        'fill-color': defaultStyle.road.sidewalk.section?.fill.color,
        'fill-outline-color': 'hsl(35, 10%, 83%)',
        'fill-pattern': 'pedestrian-polygon',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 16, 0, 16.25, 1],
      },
    },
    {
      id: 'road-sidewalk-section-fill-3',
      type: 'fill',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        ['match', ['get', 'class'], ['street_limited'], true, false],
      ],
      paint: {
        'fill-color': defaultStyle.road.sidewalk.section?.fill.color,
        'fill-outline-color': '#d6d9e6',
      },
    },
    {
      id: 'road-sidewalk-section-fill-4',
      type: 'line',
      source: 'line_source',
      'source-layer': 'line',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': defaultStyle.road.sidewalk.section?.fill.color,
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          0.5,
          18,
          12,
        ],
      },
      filter: [
        'match',
        ['get', 'type'],
        ['pedestrian', 'footway'],
        true,
        false,
      ],
    },
    {
      id: 'road-sidewalk-section-fill-5',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['get', 'class'], 'pedestrian'],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          0.5,
          18,
          12,
        ],
        'line-color': defaultStyle.road.sidewalk.section?.fill.color,
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [1, 0]],
          15,
          ['literal', [1.5, 0.4]],
          16,
          ['literal', [1, 0.2]],
        ],
      },
    },
    {
      id: 'road-sidewalk-section-fill-6',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 14,
      filter: [
        'all',
        ['==', ['get', 'type'], 'steps'],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          0.5,
          18,
          12,
        ],
        'line-color': defaultStyle.road.sidewalk.section?.fill.color,
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [1, 0]],
          15,
          ['literal', [1.75, 1]],
          16,
          ['literal', [1, 0.75]],
          17,
          ['literal', [0.3, 0.3]],
        ],
      },
    },
    {
      id: 'road-sidewalk-section-fill-7',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      metadata: { 'mapbox:group': '1444855786460.0557' },
      minzoom: 12,
      filter: [
        'all',
        ['==', ['get', 'class'], 'path'],
        [
          'step',
          ['zoom'],
          [
            '!',
            [
              'match',
              ['get', 'type'],
              ['steps', 'sidewalk', 'crossing'],
              true,
              false,
            ],
          ],
          16,
          ['!=', ['get', 'type'], 'steps'],
        ],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          0.5,
          18,
          12,
        ],
        'line-color': defaultStyle.road.sidewalk.section?.fill.color,
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [1, 0]],
          15,
          ['literal', [1.75, 1]],
          16,
          ['literal', [1, 0.75]],
          17,
          ['literal', [1, 0.5]],
        ],
      },
    },
    {
      id: 'road-sidewalk-section-fill-8',
      type: 'line',
      source: 'polygon_source',
      'source-layer': 'polygon',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': defaultStyle.road.sidewalk.section?.fill.color,
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          14,
          0.5,
          18,
          12,
        ],
      },
      filter: ['match', ['get', 'type'], 'city_wall', true, false],
    },
    {
      id: 'transit-airport-section-fill',
      type: 'fill',
      source: 'composite',
      'source-layer': 'landuse',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'fill-color': defaultStyle.transit.airport.section?.fill.color,
      },
      filter: ['==', ['get', 'class'], 'airport'],
    },
    {
      id: 'transit-airport-section-fill-2',
      type: 'fill',
      source: 'composite',
      'source-layer': 'aeroway',
      minzoom: 11,
      filter: [
        'all',
        ['==', ['geometry-type'], 'Polygon'],
        [
          'match',
          ['get', 'type'],
          ['runway', 'taxiway', 'helipad'],
          true,
          false,
        ],
      ],
      layout: {},
      paint: {
        'fill-color': defaultStyle.transit.airport.section?.fill.color,
      },
    },
    {
      id: 'transit-airport-section-stroke',
      type: 'line',
      source: 'composite',
      'source-layer': 'aeroway',
      minzoom: 9,
      filter: ['==', ['geometry-type'], 'LineString'],
      layout: {},
      paint: {
        'line-color': defaultStyle.transit.airport.section?.stroke.color,
        'line-width': [
          'interpolate',
          ['exponential', 1.5],
          ['zoom'],
          9,
          ['match', ['get', 'type'], 'runway', 1, 'taxiway', 0.5, 0.5],
          18,
          ['match', ['get', 'type'], 'runway', 80, 'taxiway', 20, 20],
        ],
      },
    },
    {
      id: 'transit-rail-section-stroke',
      type: 'line',
      source: 'line_source',
      'source-layer': 'line',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': defaultStyle.transit.rail.section?.stroke.color,
        'line-width': defaultStyle.transit.rail.section?.stroke.weight,
      },
      filter: ['match', ['get', 'type'], 'rail', true, false],
    },
    {
      id: 'transit-rail-section-stroke-2',
      type: 'line',
      source: 'composite',
      'source-layer': 'road',
      layout: {
        visibility: 'visible',
        'line-join': 'round',
      },
      minzoom: 13,

      paint: {
        'line-color': defaultStyle.transit.rail.section?.stroke.color,
        'line-width': defaultStyle.transit.rail.section?.stroke.weight,
      },
      filter: [
        'all',
        ['match', ['get', 'class'], ['major_rail', 'minor_rail'], true, false],
        ['match', ['get', 'structure'], ['none', 'ford'], true, false],
      ],
    },
    {
      id: 'transit-subway-section-stroke',
      type: 'line',
      source: 'line_source',
      'source-layer': 'line',
      layout: {
        visibility: 'visible',
      },
      paint: {
        'line-color': defaultStyle.transit.subway.section?.stroke.color,
        'line-width': defaultStyle.transit.subway.section?.stroke.weight,
      },
      filter: ['==', ['get', 'type'], 'subway'],
    },
    {
      id: 'administrative-country-section-stroke',
      type: 'line',
      metadata: { 'mapbox:group': '1444934295202.7542' },
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: {},
      paint: {
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 3.5, 10, 8],
        'line-color': defaultStyle.administrative.country.section?.stroke.color,
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 3, 0, 4, 0.5],
        'line-translate': [0, 0],
        'line-blur': ['interpolate', ['linear'], ['zoom'], 3, 0, 10, 2],
      },
    },
    {
      id: 'administrative-state-section-stroke',
      type: 'line',
      metadata: { 'mapbox:group': '1444934295202.7542' },
      source: 'composite',
      'source-layer': 'admin',
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 1],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'bevel' },
      paint: {
        'line-color': defaultStyle.administrative.state.section?.fill.color,
        'line-width': ['interpolate', ['linear'], ['zoom'], 7, 3.75, 12, 5.5],
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 7, 0, 8, 0.75],
        'line-dasharray': [1, 0],
        'line-translate': [0, 0],
        'line-blur': ['interpolate', ['linear'], ['zoom'], 3, 0, 8, 3],
      },
    },
    {
      id: 'administrative-country-section-stroke-2',
      type: 'line',
      metadata: { 'mapbox:group': '1444934295202.7542' },
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'disputed'], 'false'],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': defaultStyle.administrative.country.section?.stroke.color,
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 10, 2],
      },
    },
    {
      id: 'administrative-state-section-stroke-2',
      type: 'line',
      metadata: { 'mapbox:group': '1444934295202.7542' },
      source: 'composite',
      'source-layer': 'admin',
      filter: [
        'all',
        ['==', ['get', 'admin_level'], 1],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [2, 0]],
          7,
          ['literal', [2, 2, 6, 2]],
        ],
        'line-width': ['interpolate', ['linear'], ['zoom'], 7, 0.75, 12, 1.5],
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 2, 0, 3, 1],
        'line-color': defaultStyle.administrative.state.section?.fill.color,
      },
    },

    {
      id: 'administrative-country-section-stroke-3',
      type: 'line',
      metadata: { 'mapbox:group': '1444934295202.7542' },
      source: 'composite',
      'source-layer': 'admin',
      minzoom: 1,
      filter: [
        'all',
        ['==', ['get', 'disputed'], 'true'],
        ['==', ['get', 'admin_level'], 0],
        ['==', ['get', 'maritime'], 'false'],
        ['match', ['get', 'worldview'], ['all', 'US'], true, false],
      ],
      layout: { 'line-join': 'round' },
      paint: {
        'line-dasharray': [1.5, 1.5],
        'line-color': defaultStyle.administrative.country.section?.stroke.color,
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.5, 10, 2],
      },
    },
    {
      id: 'landscape-building-labelText',
      type: 'symbol',
      metadata: {},
      source: 'composite',
      'source-layer': 'housenum_label',
      minzoom: 17,
      layout: {
        'text-field': ['get', 'house_num'],
        'text-font': ['DIN Offc Pro Italic', 'Arial Unicode MS Regular'],
        'text-padding': 4,
        'text-max-width': 7,
        'text-size': 9.5,
      },
      paint: {
        'text-color': defaultStyle.landscape.building.labelText?.fill.color,
        'text-halo-color':
          defaultStyle.landscape.building.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.landscape.building.labelText?.stroke.weight,
      },
    },
    {
      id: 'landscape-building-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'building'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-color': defaultStyle.landscape.building.labelText?.fill.color,
        'text-halo-color':
          defaultStyle.landscape.building.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.landscape.building.labelText?.stroke.weight,
      },
    },
    {
      id: 'landscape-natural-labelText',
      type: 'symbol',
      metadata: {},
      source: 'composite',
      'source-layer': 'natural_label',
      minzoom: 4,
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['dock', 'glacier', 'landform', 'water_feature', 'wetland'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'Point'],
        ['<=', ['get', 'filterrank'], 2],
      ],
      layout: {
        'text-size': [
          'step',
          ['zoom'],
          ['step', ['get', 'sizerank'], 18, 5, 12],
          17,
          ['step', ['get', 'sizerank'], 18, 13, 12],
        ],
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': [
          'step',
          ['zoom'],
          ['step', ['get', 'sizerank'], 'center', 5, 'top'],
          17,
          ['step', ['get', 'sizerank'], 'center', 13, 'top'],
        ],
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': [
          'step',
          ['zoom'],
          ['step', ['get', 'sizerank'], 0, 5, 1],
          17,
          ['step', ['get', 'sizerank'], 0, 13, 1],
        ],
        'text-halo-blur': 0.5,
        'text-color': defaultStyle.landscape.natural.labelText?.fill.color,
        'text-halo-color':
          defaultStyle.landscape.natural.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.landscape.natural.labelText?.stroke.weight,
      },
    },
    {
      id: 'water-all-labelText-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'natural_label',
      minzoom: 13,
      filter: [
        'all',
        ['match', ['get', 'class'], ['canal', 'river', 'stream'], true, false],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: {
        'text-max-angle': 30,
        'symbol-spacing': [
          'interpolate',
          ['linear', 1],
          ['zoom'],
          15,
          250,
          17,
          400,
        ],
        'text-size': ['interpolate', ['linear'], ['zoom'], 13, 12, 18, 16],
        'symbol-placement': 'line',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: { 'text-color': defaultStyle.water.all.labelText?.fill.color },
    },
    {
      id: 'water-all-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'natural_label',
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['bay', 'ocean', 'reservoir', 'sea', 'water'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'LineString'],
      ],
      layout: {
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          ['step', ['get', 'sizerank'], 24, 6, 18, 12, 12],
          10,
          ['step', ['get', 'sizerank'], 18, 9, 12],
          18,
          ['step', ['get', 'sizerank'], 18, 9, 16],
        ],
        'text-max-angle': 30,
        'text-letter-spacing': [
          'match',
          ['get', 'class'],
          'ocean',
          0.25,
          ['sea', 'bay'],
          0.15,
          0,
        ],
        'symbol-placement': 'line-center',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'text-color': defaultStyle.water.all.labelText?.fill.color,
      },
    },
    {
      id: 'water-all-labelText-3',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'natural_label',
      filter: [
        'all',
        [
          'match',
          ['get', 'class'],
          ['bay', 'ocean', 'reservoir', 'sea', 'water'],
          true,
          false,
        ],
        ['==', ['geometry-type'], 'Point'],
      ],
      layout: {
        'text-line-height': 1.3,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          ['step', ['get', 'sizerank'], 24, 6, 18, 12, 12],
          10,
          ['step', ['get', 'sizerank'], 18, 9, 12],
        ],
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-letter-spacing': [
          'match',
          ['get', 'class'],
          'ocean',
          0.25,
          ['bay', 'sea'],
          0.15,
          0.01,
        ],
        'text-max-width': [
          'match',
          ['get', 'class'],
          'ocean',
          4,
          'sea',
          5,
          ['bay', 'water'],
          7,
          10,
        ],
      },
      paint: {
        'text-color': defaultStyle.water.all.labelText?.fill.color,
      },
    },
    {
      id: 'transit-bus-labelText',
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-field': ['get', 'name'],
        'text-size': 12,
        visibility: 'visible',
      },
      paint: {
        'text-color': defaultStyle.transit.bus.labelText?.fill.color,
        'text-halo-color': defaultStyle.transit.bus.labelText?.stroke.color,
        'text-halo-width': defaultStyle.transit.bus.labelText?.stroke.weight,
      },
      filter: ['==', ['get', 'type'], 'bus_stop'],
    },
    {
      id: 'transit-airport-labelText',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'airport_label',
      minzoom: 8,
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['get', 'sizerank'],
          ['concat', ['get', 'maki'], '-15'],
          12,
          ['concat', ['get', 'maki'], '-11'],
        ],
        'text-offset': [0, 0.75],
        'text-rotation-alignment': 'viewport',
        'text-anchor': 'top',
        'text-field': [
          'step',
          ['get', 'sizerank'],
          ['coalesce', ['get', 'name_en'], ['get', 'name']],
          15,
          ['get', 'ref'],
        ],
        'text-max-width': 9,
      },
      paint: {
        'text-color': defaultStyle.transit.airport.labelText?.fill.color,
        'text-halo-color': defaultStyle.transit.airport.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.transit.airport.labelText?.stroke.weight,
      },
    },
    {
      id: 'road-arterial-labelIcon-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'motorway_junction',
      metadata: {},
      minzoom: 14,
      filter: ['all', ['has', 'reflen'], ['<=', ['get', 'reflen'], 9]],
      layout: {
        'text-field': ['get', 'ref'],
        'text-size': 9,
        'icon-image': [
          'concat',
          'motorway-exit-',
          ['to-string', ['get', 'reflen']],
        ],
        'text-font': ['DIN Offc Pro Bold', 'Arial Unicode MS Bold'],
      },
      paint: { 'text-color': 'hsl(0, 0%, 100%)', 'text-translate': [0, 0] },
    },
    {
      id: 'road-arterial-labelIcon-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      minzoom: 6,
      filter: [
        'all',
        ['has', 'reflen'],
        ['<=', ['get', 'reflen'], 6],
        [
          'step',
          ['zoom'],
          ['==', ['geometry-type'], 'Point'],
          11,
          ['>', ['get', 'len'], 5000],
          12,
          ['>', ['get', 'len'], 2500],
          13,
          ['>', ['get', 'len'], 1000],
          14,
          true,
        ],
      ],
      layout: {
        'text-size': 9,
        'icon-image': [
          'concat',
          ['get', 'shield'],
          '-',
          ['to-string', ['get', 'reflen']],
        ],
        'icon-rotation-alignment': 'viewport',
        'text-max-angle': 38,
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          150,
          14,
          200,
        ],
        'text-font': ['DIN Offc Pro Bold', 'Arial Unicode MS Bold'],
        'symbol-placement': ['step', ['zoom'], 'point', 11, 'line'],
        'text-rotation-alignment': 'viewport',
        'text-field': ['get', 'ref'],
        'text-letter-spacing': 0.05,
      },
      paint: {
        'text-color': [
          'match',
          ['get', 'shield_text_color'],
          'white',
          'hsl(0, 0%, 100%)',
          'black',
          'hsl(0, 0%, 7%)',
          'yellow',
          'hsl(50, 100%, 70%)',
          'orange',
          'hsl(25, 100%, 75%)',
          'blue',
          'hsl(230, 48%, 34%)',
          'hsl(0, 0%, 100%)',
        ],
      },
    },
    {
      id: 'road-sidewalk-labelText-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      minzoom: 10,
      filter: [
        'match',
        ['get', 'class'],
        ['pedestrian', 'street_limited'],
        true,
        false,
      ],
      layout: {
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          ['match', ['get', 'class'], ['pedestrian', 'street_limited'], 9, 6.5],
          18,
          ['match', ['get', 'class'], ['pedestrian', 'street_limited'], 14, 13],
        ],
        'text-max-angle': 30,
        'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
        'symbol-placement': 'line',
        'text-padding': 1,
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-letter-spacing': 0.01,
      },
      paint: {
        'text-color': defaultStyle.road.sidewalk.labelText?.fill.color,
        'text-halo-color': defaultStyle.road.sidewalk.labelText?.stroke.color,
        'text-halo-width': defaultStyle.road.sidewalk.labelText?.stroke.weight,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'road-local-labelText-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      minzoom: 10,
      filter: ['match', ['get', 'class'], ['street'], true, false],
      layout: {
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          ['match', ['get', 'class'], ['street'], 9, 6.5],
          18,
          ['match', ['get', 'class'], ['street'], 14, 13],
        ],
        'text-max-angle': 30,
        'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
        'symbol-placement': 'line',
        'text-padding': 1,
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-letter-spacing': 0.01,
      },
      paint: {
        'text-color': defaultStyle.road.local.labelText?.fill.color,
        'text-halo-color': defaultStyle.road.local.labelText?.stroke.color,
        'text-halo-width': defaultStyle.road.local.labelText?.stroke.weight,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'road-arterial-labelText-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'road',
      metadata: {},
      minzoom: 10,
      filter: [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'class'],
          ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'],
          true,
          false,
        ],
        12,
        [
          'match',
          ['get', 'class'],
          ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'],
          true,
          false,
        ],
      ],
      layout: {
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          [
            'match',
            ['get', 'class'],
            ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'],
            10,
            [
              'motorway_link',
              'trunk_link',
              'primary_link',
              'secondary_link',
              'tertiary_link',
            ],
            9,
            6.5,
          ],
          18,
          [
            'match',
            ['get', 'class'],
            ['motorway', 'trunk', 'primary', 'secondary', 'tertiary'],
            16,
            [
              'motorway_link',
              'trunk_link',
              'primary_link',
              'secondary_link',
              'tertiary_link',
            ],
            14,
            13,
          ],
        ],
        'text-max-angle': 30,
        'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
        'symbol-placement': 'line',
        'text-padding': 1,
        'text-rotation-alignment': 'map',
        'text-pitch-alignment': 'viewport',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-letter-spacing': 0.01,
      },
      paint: {
        'text-color': defaultStyle.road.arterial.labelText?.fill.color,
        'text-halo-color': defaultStyle.road.arterial.labelText?.stroke.color,
        'text-halo-width': defaultStyle.road.arterial.labelText?.stroke.weight,
        'text-halo-blur': 0.5,
      },
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-color': defaultStyle.poi.landmark.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.landmark.labelText?.stroke.weight,
        'text-halo-blur': 0.5,
        'text-color': defaultStyle.poi.landmark.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['milestone', 'arts_centre', 'fountain'],
        true,
        false,
      ],
      id: 'poi-landmark-labelText-3',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.business.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.business.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.business.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        [
          'cinema',
          'bar',
          'post_box',
          'restaurant',
          'theatre',
          'studio',
          'bureau_de_change',
          'marketplace',
          'fast_food',
          'toll_booth',
          'charging_station',
          'social_facility',
          'nightclub',
          'food_court',
          'car_rental',
          'bicycle_rental',
          'pub',
          'bank',
          'ice_cream',
          'fuel',
        ],
        true,
        false,
      ],
      id: 'poi-business-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.government.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.government.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.government.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        [
          'townhall',
          'social_centre',
          'post_office',
          'shelter',
          'embassy',
          'police',
        ],
        true,
        false,
      ],
      id: 'poi-government-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.medical.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.medical.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.medical.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['hospital', 'doctors', 'clinic', 'dentist', 'pharmacy'],
        true,
        false,
      ],
      id: 'poi-medical-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.park.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.park.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.park.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['waste_basket', 'tree', 'rest_area'],
        true,
        false,
      ],
      id: 'poi-park-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.worship.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.worship.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.worship.labelText?.fill.color,
      },
      filter: ['match', ['get', 'type'], ['place_of_worship'], true, false],
      id: 'poi-worship-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.school.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.school.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.school.labelText?.fill.color,
      },
      filter: [
        'match',
        ['get', 'type'],
        ['school', 'kindergarten', 'college'],
        true,
        false,
      ],
      id: 'poi-school-labelText-1',
    },
    {
      type: 'symbol',
      source: 'poi_source',
      'source-layer': 'poi',
      layout: {
        'text-size': 12,
        'text-field': ['get', 'name'],
        visibility: 'visible',
      },
      paint: {
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.etc.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.etc.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.etc.labelText?.fill.color,
      },
      filter: [
        'in',
        'type',
        'parking',
        'crossing',
        'traffic_signal',
        'mini_roundabout',
        'bench',
        'sally port',
        'block',
        'street_lamp',
        'bollard',
        'lift_gate',
        'gate',
        'elevator',
        'toilets',
        'water_point',
        'spring',
        'atm',
      ],
      id: 'poi-etc-labelText-1',
    },
    {
      id: 'poi-business-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'food_and_drink'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-color': defaultStyle.poi.business.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.business.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.business.labelText?.fill.color,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'poi-park-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'park_like'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.park.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.park.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.park.labelText?.fill.color,
      },
    },
    {
      id: 'poi-school-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'education'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.school.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.school.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.school.labelText?.fill.color,
      },
    },
    {
      id: 'poi-medical-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'medical'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.medical.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.medical.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.medical.labelText?.fill.color,
      },
    },
    {
      id: 'poi-landmark-labelText-1',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'arts_and_entertainment'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-color': defaultStyle.poi.landmark.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.landmark.labelText?.stroke.weight,
        'text-halo-blur': 0.5,
        'text-color': defaultStyle.poi.landmark.labelText?.fill.color,
      },
    },
    {
      id: 'poi-landmark-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'landmark'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-color': defaultStyle.poi.landmark.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.landmark.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.landmark.labelText?.fill.color,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'poi-government-labelText-3',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'general'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.government.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.government.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.government.labelText?.fill.color,
      },
    },
    {
      id: 'poi-etc-labelText-3',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'historic'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.etc.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.etc.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.etc.labelText?.fill.color,
      },
    },
    {
      id: 'poi-etc-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'industrial'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.etc.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.etc.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.etc.labelText?.fill.color,
      },
    },
    {
      id: 'poi-government-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'public_facilities'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.government.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.government.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.government.labelText?.fill.color,
      },
    },
    {
      id: 'poi-worship-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'religion'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.worship.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.worship.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.worship.labelText?.fill.color,
      },
    },
    {
      id: 'poi-business-labelText-3',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'store_like'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-color': defaultStyle.poi.business.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.business.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.business.labelText?.fill.color,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'poi-sports-labelText',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'poi_label',
      metadata: {},
      minzoom: 6,
      filter: ['==', ['get', 'class'], 'sport_and_leisure'],
      layout: {
        'text-size': 12,
        'icon-image': [
          'step',
          ['zoom'],
          ['concat', ['get', 'maki'], '-11'],
          15,
          ['concat', ['get', 'maki'], '-15'],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            5,
            ['literal', [0, 0.75]],
          ],
          17,
          [
            'step',
            ['get', 'sizerank'],
            ['literal', [0, 0]],
            13,
            ['literal', [0, 0.75]],
          ],
        ],
        'text-anchor': 'top',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
      },
      paint: {
        'icon-opacity': 1,
        'text-halo-blur': 0.5,
        'text-halo-color': defaultStyle.poi.sports.labelText?.stroke.color,
        'text-halo-width': defaultStyle.poi.sports.labelText?.stroke.weight,
        'text-color': defaultStyle.poi.sports.labelText?.fill.color,
      },
    },
    {
      id: 'administrative-locality-labelText-2',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 10,
      maxzoom: 15,
      filter: [
        'all',
        ['==', ['get', 'class'], 'settlement_subdivision'],
        ['<=', ['get', 'filterrank'], 4],
      ],
      layout: {
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-transform': 'uppercase',
        'text-letter-spacing': [
          'match',
          ['get', 'type'],
          'suburb',
          0.15,
          ['quarter', 'neighborhood'],
          0.1,
          0.1,
        ],
        'text-max-width': 7,
        'text-padding': 3,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.5, 0, 1, 1],
          ['zoom'],
          11,
          [
            'match',
            ['get', 'type'],
            'suburb',
            11,
            ['quarter', 'neighborhood'],
            10.5,
            10.5,
          ],
          15,
          [
            'match',
            ['get', 'type'],
            'suburb',
            17,
            ['quarter', 'neighborhood'],
            16,
            16,
          ],
        ],
      },
      paint: {
        'text-halo-color':
          defaultStyle.administrative.locality.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.administrative.locality.labelText?.stroke.weight,
        'text-color':
          defaultStyle.administrative.locality.labelText?.fill.color,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'administrative-locality-labelText',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'place_label',
      maxzoom: 15,
      filter: [
        'all',
        ['<=', ['get', 'filterrank'], 3],
        ['==', ['get', 'class'], 'settlement'],
        [
          'step',
          ['zoom'],
          true,
          13,
          ['>=', ['get', 'symbolrank'], 11],
          14,
          ['>=', ['get', 'symbolrank'], 13],
        ],
      ],
      layout: {
        'icon-image': [
          'case',
          ['==', ['get', 'capital'], 2],
          'border-dot-13',
          ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
        ],
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
          8,
          [
            'step',
            ['get', 'symbolrank'],
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
            11,
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
          ],
          10,
          [
            'step',
            ['get', 'symbolrank'],
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
            12,
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
          ],
          11,
          [
            'step',
            ['get', 'symbolrank'],
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
            13,
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
          ],
          12,
          [
            'step',
            ['get', 'symbolrank'],
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
            15,
            ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
          ],
          13,
          ['literal', ['DIN Offc Pro Italic', 'Arial Unicode MS Regular']],
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'capital'],
            2,
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.3]],
              'bottom-left',
              ['literal', [0.3, -0.1]],
              'left',
              ['literal', [0.45, 0.1]],
              'top-left',
              ['literal', [0.3, 0.1]],
              'top',
              ['literal', [0, 0.3]],
              'top-right',
              ['literal', [-0.3, 0.1]],
              'right',
              ['literal', [-0.45, 0]],
              'bottom-right',
              ['literal', [-0.3, -0.1]],
              ['literal', [0, -0.3]],
            ],
            [
              'match',
              ['get', 'text_anchor'],
              'bottom',
              ['literal', [0, -0.25]],
              'bottom-left',
              ['literal', [0.2, -0.05]],
              'left',
              ['literal', [0.4, 0.05]],
              'top-left',
              ['literal', [0.2, 0.05]],
              'top',
              ['literal', [0, 0.25]],
              'top-right',
              ['literal', [-0.2, 0.05]],
              'right',
              ['literal', [-0.4, 0.05]],
              'bottom-right',
              ['literal', [-0.2, -0.05]],
              ['literal', [0, -0.25]],
            ],
          ],
          8,
          ['literal', [0, 0]],
        ],
        'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
        'text-justify': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            ['bottom', 'top'],
            'center',
            ['left', 'bottom-left', 'top-left'],
            'left',
            ['right', 'bottom-right', 'top-right'],
            'right',
            'center',
          ],
          8,
          'center',
        ],
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-max-width': 7,
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.2, 0, 0.9, 1],
          ['zoom'],
          3,
          [
            'step',
            ['get', 'symbolrank'],
            12,
            9,
            11,
            10,
            10.5,
            12,
            9.5,
            14,
            8.5,
            16,
            6.5,
            17,
            4,
          ],
          15,
          [
            'step',
            ['get', 'symbolrank'],
            28,
            9,
            26,
            10,
            23,
            11,
            21,
            12,
            20,
            13,
            19,
            15,
            17,
          ],
        ],
      },
      paint: {
        'icon-opacity': ['step', ['zoom'], 1, 8, 0],
        'text-halo-blur': 1,
        'text-halo-color':
          defaultStyle.administrative.locality.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.administrative.locality.labelText?.stroke.weight,
        'text-color':
          defaultStyle.administrative.locality.labelText?.fill.color,
      },
    },
    {
      id: 'administrative-state-labelText',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 3,
      maxzoom: 9,
      filter: ['==', ['get', 'class'], 'state'],
      layout: {
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.85, 0.7, 0.65, 1],
          ['zoom'],
          4,
          ['step', ['get', 'symbolrank'], 10, 6, 9.5, 7, 9],
          9,
          ['step', ['get', 'symbolrank'], 24, 6, 18, 7, 14],
        ],
        'text-transform': 'uppercase',
        'text-field': [
          'step',
          ['zoom'],
          [
            'step',
            ['get', 'symbolrank'],
            ['coalesce', ['get', 'name_ko'], ['get', 'name']],
            5,
            ['coalesce', ['get', 'abbr'], ['get', 'name_ko'], ['get', 'name']],
          ],
          5,
          ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        ],
        'text-letter-spacing': 0.15,
        'text-max-width': 6,
      },
      paint: {
        'text-color': defaultStyle.administrative.state.labelText?.fill.color,
        'text-halo-color':
          defaultStyle.administrative.state.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.administrative.state.labelText?.stroke.weight,
      },
    },

    {
      id: 'administrative-country-labelText',
      type: 'symbol',
      source: 'composite',
      'source-layer': 'place_label',
      minzoom: 1,
      maxzoom: 10,
      filter: ['==', ['get', 'class'], 'country'],
      layout: {
        'icon-image': 'dot-11',
        'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
        'text-line-height': 1.1,
        'text-max-width': 6,
        'text-anchor': [
          'step',
          ['zoom'],
          ['coalesce', ['get', 'text_anchor'], 'center'],
          7,
          'center',
        ],
        'text-offset': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.25]],
            'bottom-left',
            ['literal', [0.2, -0.05]],
            'left',
            ['literal', [0.4, 0.05]],
            'top-left',
            ['literal', [0.2, 0.05]],
            'top',
            ['literal', [0, 0.25]],
            'top-right',
            ['literal', [-0.2, 0.05]],
            'right',
            ['literal', [-0.4, 0.05]],
            'bottom-right',
            ['literal', [-0.2, -0.05]],
            ['literal', [0, -0.25]],
          ],
          7,
          ['literal', [0, 0]],
        ],
        'text-justify': [
          'step',
          ['zoom'],
          [
            'match',
            ['get', 'text_anchor'],
            ['bottom', 'top'],
            'center',
            ['left', 'bottom-left', 'top-left'],
            'left',
            ['right', 'bottom-right', 'top-right'],
            'right',
            'center',
          ],
          7,
          'center',
        ],
        'text-size': [
          'interpolate',
          ['cubic-bezier', 0.2, 0, 0.7, 1],
          ['zoom'],
          1,
          ['step', ['get', 'symbolrank'], 11, 4, 9, 5, 8],
          9,
          ['step', ['get', 'symbolrank'], 28, 4, 22, 5, 21],
        ],
      },
      paint: {
        'icon-opacity': [
          'step',
          ['zoom'],
          ['case', ['has', 'text_anchor'], 1, 0],
          7,
          0,
        ],
        'text-color': defaultStyle.administrative.country.labelText?.fill.color,
        'text-halo-color':
          defaultStyle.administrative.country.labelText?.stroke.color,
        'text-halo-width':
          defaultStyle.administrative.country.labelText?.stroke.weight,
      },
    },
  ],
};

export default initLayers;
