import defaultStyle from '../defaultStyle';

const layers = [
  {
    id: 'landcover-section-fill',
    type: 'background',
    metadata: {},
    layout: {},
    paint: {
      'background-color': defaultStyle.landscape.landcover.section?.fill.color,
    },
  },
  {
    id: 'landcover-section-fill-2',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'landcover',
    maxzoom: 7,
    layout: {},
    paint: {
      'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
      'fill-opacity': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        2,
        0.3,
        7,
        0,
      ],
      'fill-antialias': false,
    },
  },
  {
    id: 'natural-section-fill-2',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'landuse_overlay',
    minzoom: 5,
    filter: ['==', ['get', 'class'], 'national_park'],
    layout: {},
    paint: {
      'fill-color': defaultStyle.landscape.natural.section?.fill.color,
      'fill-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        5,
        0,
        6,
        0.5,
        10,
        0.5,
      ],
    },
  },
  {
    id: 'landcover-section-fill-4',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'landuse',
    minzoom: 5,
    filter: [
      'match',
      ['get', 'class'],
      [
        'park',
        'airport',
        'cemetery',
        'glacier',
        'hospital',
        'pitch',
        'sand',
        'school',
      ],
      true,
      false,
    ],
    layout: {},
    paint: {
      'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
      'fill-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        5,
        0,
        6,
        ['match', ['get', 'class'], 'glacier', 0.5, 1],
      ],
    },
  },
  {
    id: 'natural-section-fill-3',
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': defaultStyle.landscape.natural.section?.fill.color,
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['sand', 'heath', 'grassland'],
      true,
      false,
    ],
  },
  {
    id: 'humanmade-section-stroke',
    type: 'line',
    metadata: {},
    source: 'composite',
    'source-layer': 'landuse',
    minzoom: 15,
    filter: ['==', ['get', 'class'], 'pitch'],
    layout: {},
    paint: {
      'line-color': defaultStyle?.landscape.humanmade.section?.stroke.color,
    },
  },
  {
    id: 'mountain-section-fill',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'hillshade',
    maxzoom: 16,
    layout: {},
    paint: {
      'fill-color': defaultStyle.landscape.mountain.section?.fill.color,
      'fill-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        14,
        ['match', ['get', 'level'], [67, 56], 0.06, [89, 78], 0.05, 0.12],
        16,
        0,
      ],
      'fill-antialias': false,
    },
  },
  {
    id: 'landcover-section-fill-5',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'structure',
    minzoom: 13,
    filter: [
      'all',
      ['==', ['geometry-type'], 'Polygon'],
      ['==', ['get', 'class'], 'land'],
    ],
    layout: {},
    paint: {
      'fill-color': defaultStyle.landscape.landcover.section?.fill.color,
    },
  },
  {
    id: 'landcover-section-stroke',
    type: 'line',
    metadata: {},
    source: 'composite',
    'source-layer': 'structure',
    minzoom: 13,
    filter: [
      'all',
      ['==', ['geometry-type'], 'LineString'],
      ['==', ['get', 'class'], 'land'],
    ],
    layout: { 'line-cap': 'round' },
    paint: {
      'line-width': defaultStyle.landscape.landcover.section?.stroke.weight,
      // 'line-width': [
      //   'interpolate',
      //   ['exponential', 1.99],
      //   ['zoom'],
      //   14,
      //   0.75,
      //   20,
      //   40,
      // ],
      'line-color': defaultStyle.landscape.landcover.section?.stroke.color,
    },
  },
  {
    id: 'humanmade-section-fill',
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': defaultStyle.landscape.humanmade.section?.fill.color,
      'fill-opacity': 0.7,
    },
    filter: [
      'in',
      'type',
      'civic',
      'construction',
      'gate',
      'palace',
      'parking',
      'riverbank',
      'station',
      'steps',
      'train_station',
      'shrine',
      'retaining_wall',
      'smoking_area',
      'city_gate',
      'terrace',
      'shelter',
      'wall',
      'fence',
      'toll_booth',
      'kerb',
      'bench',
      'footway',
      'pedestrian',
      'parking',
      'fountain',
      'gate',
      '',
    ],
  },
  {
    id: 'building-section-stroke',
    type: 'line',
    metadata: {},
    source: 'composite',
    'source-layer': 'building',
    minzoom: 15,
    filter: [
      'all',
      ['!=', ['get', 'type'], 'building:part'],
      ['==', ['get', 'underground'], 'false'],
    ],
    layout: {},
    paint: {
      'line-color': defaultStyle.landscape.building.section?.stroke.color,
      'line-width': defaultStyle.landscape.building.section?.stroke.weight,
      // 'line-width': [
      //   'interpolate',
      //   ['exponential', 1.5],
      //   ['zoom'],
      //   15,
      //   0.75,
      //   20,
      //   3,
      // ],
      'line-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
    },
  },
  {
    id: 'building-section-fill',
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': defaultStyle.landscape.building.section?.fill.color,
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
      'fill-outline-color': 'hsl(35, 8%, 80%)',
    },
    filter: [
      'in',
      'type',
      'apartments',
      'bunker',
      'cathedral',
      'chapel',
      'childcare',
      'chungmoo art hall',
      'church',
      'courthouse',
      'government',
      'hospital',
      'hotel',
      'house',
      'kindergarten',
      'public',
      'ranger_station',
      'residential',
      'roof',
      'school',
      'shed',
      'shelter',
      'university',
      'warehouse',
      'company',
      'conference_centre',
      'pavilion',
      'swimming_pool',
      'office',
      'dormitory',
      'public_bath',
      'community_centre',
      'theatre',
      'fire_station',
      'post_office',
      'police',
      'townhall',
      'public',
      'college',
      'language_school',
      'arts_centre',
      'palace',
      'toilets',
      'social_facility',
      'restaurant',
      'cafe',
      'marketplace',
      'fast_food',
      'bar',
      'pub',
      'casino',
      'cinema',
      '',
    ],
  },
  {
    id: 'building-section-fill-2',
    type: 'fill',
    metadata: {},
    source: 'composite',
    'source-layer': 'building',
    minzoom: 15,
    filter: [
      'all',
      ['!=', ['get', 'type'], 'building:part'],
      ['==', ['get', 'underground'], 'false'],
    ],
    layout: {},
    paint: {
      'fill-color': [
        'interpolate',
        ['linear'],
        ['zoom'],
        15,
        defaultStyle.landscape.building.section?.fill.color,
        16,
        'hsl(35, 8%, 85%)',
      ],
      'fill-opacity': ['interpolate', ['linear'], ['zoom'], 15, 0, 16, 1],
      'fill-outline-color': 'hsl(35, 6%, 79%)',
    },
  },
  {
    id: 'building-labelText',
    type: 'symbol',
    metadata: {},
    source: 'composite',
    'source-layer': 'housenum_label',
    minzoom: 17,
    layout: {
      'text-field': ['get', 'house_num'],
      'text-font': ['DIN Offc Pro Italic', 'Arial Unicode MS Regular'],
      'text-padding': 4,
      'text-max-width': 7,
      'text-size': 9.5,
    },
    paint: {
      'text-color': defaultStyle.landscape.building.labelText?.fill.color,
      'text-halo-color':
        defaultStyle.landscape.building.labelText?.stroke.color,
      'text-halo-width':
        defaultStyle.landscape.building.labelText?.stroke.weight,
    },
  },
  {
    id: 'building-labelText-2',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'poi_label',
    metadata: {},
    minzoom: 6,
    filter: ['==', ['get', 'class'], 'building'],
    layout: {
      'text-size': 12,
      'icon-image': [
        'step',
        ['zoom'],
        ['concat', ['get', 'maki'], '-11'],
        15,
        ['concat', ['get', 'maki'], '-15'],
      ],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'step',
          ['get', 'sizerank'],
          ['literal', [0, 0]],
          5,
          ['literal', [0, 0.75]],
        ],
        17,
        [
          'step',
          ['get', 'sizerank'],
          ['literal', [0, 0]],
          13,
          ['literal', [0, 0.75]],
        ],
      ],
      'text-anchor': 'top',
      'text-field': ['coalesce', ['get', 'name_ko'], ['get', 'name']],
    },
    paint: {
      'icon-opacity': 1,
      'text-halo-color':
        defaultStyle.landscape.building.labelText?.stroke.color,
      'text-halo-width':
        defaultStyle.landscape.building.labelText?.stroke.weight,
      'text-halo-blur': 0.5,
      'text-color': defaultStyle.landscape.building.labelText?.fill.color,
    },
  },
  {
    id: 'natural-section-fill',
    type: 'fill',
    source: 'polygon_source',
    'source-layer': 'polygon',
    layout: {
      visibility: 'visible',
    },
    paint: {
      'fill-color': defaultStyle.landscape.natural.section?.fill.color,
      'fill-opacity': 0.5,
    },
    filter: [
      'match',
      ['get', 'type'],
      ['wood', 'scrub', 'bare_rock'],
      true,
      false,
    ],
  },
  {
    id: 'natural-labelText',
    type: 'symbol',
    metadata: {},
    source: 'composite',
    'source-layer': 'natural_label',
    minzoom: 4,
    filter: [
      'all',
      [
        'match',
        ['get', 'class'],
        ['dock', 'glacier', 'landform', 'water_feature', 'wetland'],
        true,
        false,
      ],
      ['==', ['geometry-type'], 'Point'],
      ['<=', ['get', 'filterrank'], 2],
    ],
    layout: {
      'text-size': [
        'step',
        ['zoom'],
        ['step', ['get', 'sizerank'], 18, 5, 12],
        17,
        ['step', ['get', 'sizerank'], 18, 13, 12],
      ],
      'icon-image': [
        'step',
        ['zoom'],
        ['concat', ['get', 'maki'], '-11'],
        15,
        ['concat', ['get', 'maki'], '-15'],
      ],
      'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'step',
          ['get', 'sizerank'],
          ['literal', [0, 0]],
          5,
          ['literal', [0, 0.75]],
        ],
        17,
        [
          'step',
          ['get', 'sizerank'],
          ['literal', [0, 0]],
          13,
          ['literal', [0, 0.75]],
        ],
      ],
      'text-anchor': [
        'step',
        ['zoom'],
        ['step', ['get', 'sizerank'], 'center', 5, 'top'],
        17,
        ['step', ['get', 'sizerank'], 'center', 13, 'top'],
      ],
      'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
    },
    paint: {
      'icon-opacity': [
        'step',
        ['zoom'],
        ['step', ['get', 'sizerank'], 0, 5, 1],
        17,
        ['step', ['get', 'sizerank'], 0, 13, 1],
      ],
      'text-halo-color': defaultStyle.landscape.natural.labelText?.stroke.color,
      'text-halo-width':
        defaultStyle.landscape.natural.labelText?.stroke.weight,
      'text-halo-blur': 0.5,
      'text-color': defaultStyle.landscape.natural.labelText?.fill.color,
    },
  },
];

export default layers;
