export const arterialLayerNames = {
  all: [
    'road-arterial-section-fill-1',
    'road-arterial-section-fill-2',
    'road-arterial-section-fill-3',
    'road-arterial-section-fill-4',
    'road-arterial-section-fill-5',
    'road-arterial-section-fill-6',
    'road-arterial-section-fill-7',
    'road-arterial-section-fill-8',
    'road-arterial-section-fill-9',
    'road-arterial-section-fill-10',
    'road-arterial-section-fill-11',
    'road-arterial-section-fill-12',
    'road-arterial-section-fill-13',
    'road-arterial-section-fill-14',
    'road-arterial-section-fill-15',
    'road-arterial-section-stroke-1',
    'road-arterial-section-stroke-2',
    'road-arterial-section-stroke-3',
    'road-arterial-section-stroke-4',
    'road-arterial-section-stroke-5',
    'road-arterial-section-stroke-6',
    'road-arterial-labelText-1',
    'road-arterial-labelIcon-1',
    'road-arterial-labelIcon-2',
  ],
  polygon: ['road-arterial-section-fill-1'],
  line: [
    'road-arterial-section-fill-2',
    'road-arterial-section-fill-3',
    'road-arterial-section-fill-4',
    'road-arterial-section-fill-5',
    'road-arterial-section-fill-6',
    'road-arterial-section-fill-7',
    'road-arterial-section-fill-8',
    'road-arterial-section-fill-9',
    'road-arterial-section-fill-10',
    'road-arterial-section-fill-11',
    'road-arterial-section-fill-12',
    'road-arterial-section-fill-13',
    'road-arterial-section-fill-14',
    'road-arterial-section-fill-15',
  ],
  stroke: [
    'road-arterial-section-stroke-1',
    'road-arterial-section-stroke-2',
    'road-arterial-section-stroke-3',
    'road-arterial-section-stroke-4',
    'road-arterial-section-stroke-5',
    'road-arterial-section-stroke-6',
  ],
  text: {
    all: ['road-arterial-labelText-1'],
    hasStroke: ['road-arterial-labelText-1'],
    noStroke: [],
  },
  icon: ['road-arterial-labelIcon-1', 'road-arterial-labelIcon-2'],
};
