export const arterialLayerNames = {
  all: [
    'road-arterial-polygon',
    'road-arterial',
    'road-primary',
    'road-secondary-tertiary',
    'road-motorway-trunk',
    'road-minor',
    'road-minor-low',
    'road-primary-case',
    'road-secondary-tertiary-case',
    'road-motorway-trunk-case',
    'road-minor-case',
    'road-minor-low',
    'road-number-shield',
    'road-exit-shield',
    'road-arterial-label',
    'road-major-link',
    'bridge-motorway-trunk',
    'bridge-motorway-trunk-2',
    'bridge-major-link',
    'bridge-major-link-2',
    'bridge-path',
    'bridge-path-bg',
    'bridge-primary-secondary-tertiary',
    'bridge-major-link-case',
    'bridge-primary-secondary-tertiary-case',
  ],
  polygon: ['road-arterial-polygon'],
  line: [
    'road-arterial',
    'road-primary',
    'road-secondary-tertiary',
    'road-motorway-trunk',
    'road-minor',
    'road-minor-low',
    'road-major-link',
    'bridge-motorway-trunk',
    'bridge-motorway-trunk-2',
    'bridge-major-link',
    'bridge-major-link-2',
    'bridge-path',
    'bridge-path-bg',
    'bridge-primary-secondary-tertiary',
  ],
  stroke: [
    'road-primary-case',
    'road-secondary-tertiary-case',
    'road-motorway-trunk-case',
    'road-minor-case',
    'bridge-major-link-case',
    'bridge-primary-secondary-tertiary-case',
  ],
  text: {
    all: ['road-number-shield', 'road-exit-shield', 'road-arterial-label'],
    hasStroke: ['road-arterial-label'],
    noStroke: ['road-number-shield', 'road-exit-shield'],
  },
  icon: [],
};
